spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.143.254:3306/sell?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    database: 1
    host: 134.175.143.254
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 600
        max-wait: 1000
        max-idle: 300
        min-idle: 100
    timeout: 2500
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

mybatis:
  type-aliases-package: com.cimc.po
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

server:
  servlet:
    context-path: /sell
  port: 8080


ftp:
  ip: 134.175.143.254
  port: 21
  username: leo
  password: 123456
  imgpath: img
  videopath: video
  imgport: 8090
  videoport: 8091